name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:

      # 1. Checkout your repo
      - uses: actions/checkout@v3

      # 2. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # 3. Initialize (downloads providers, etc)
      - name: Terraform Init
        run: terraform init

      # 4. Validate syntax
      - name: Terraform Validate
        run: terraform validate

      # 5. Show plan
      - name: Terraform Plan
        run: terraform plan

      # 6. Apply changes (auto-approve)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
